default: &default
  adapter: sqlite3
  encoding: unicode

development:
  <<: *default
  database: "db/planner_development.db"

test:
  <<: *default
  database: "db/planner_test.db"

production:
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch('RAILS_DB_USERNAME') { 'username' } %>
  password: <%= ENV.fetch('RAILS_DB_PASSWORD') { 'password' } %>
  host: <%= ENV.fetch('RAILS_DB_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('RAILS_DB_PORT') { 5432 } %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  database: <%= ENV.fetch('RAILS_DB_PRODUCTION') { 'planner_production' } %>
  timeout: 5000
